(function() {
  'use strict';

  if (document.getElementById('decidr-theme')) return;

  var style = document.createElement('style');
  style.id = 'decidr-theme';

  var css = ''
    + ':root {'
    + '  --glass-bg: rgba(255,255,255,0.06);'
    + '  --glass-bg-heavy: rgba(255,255,255,0.1);'
    + '  --glass-blur: 12px;'
    + '  --glass-border: rgba(255,255,255,0.1);'
    + '  --glass-shadow: 0 8px 32px rgba(0,0,0,0.4);'
    + '  --glass-shadow-elevated: 0 12px 40px rgba(0,0,0,0.5);'
    + '  --glass-inset-highlight: inset 0 1px 0 rgba(255,255,255,0.06);'
    + '  --bg-app: #0f1117;'
    + '  --bg-surface: rgba(255,255,255,0.05);'
    + '  --bg-surface-hover: rgba(255,255,255,0.08);'
    + '  --bg-surface-subtle: rgba(255,255,255,0.03);'
    + '  --text-primary: rgba(255,255,255,0.95);'
    + '  --text-secondary: rgba(255,255,255,0.6);'
    + '  --text-tertiary: rgba(255,255,255,0.35);'
    + '  --accent-primary: #818cf8;'
    + '  --accent-primary-hover: #6366f1;'
    + '  --accent-primary-ghost: rgba(129,140,248,0.1);'
    + '  --border-default: rgba(255,255,255,0.08);'
    + '  --border-subtle: rgba(255,255,255,0.04);'
    + '  --border-strong: rgba(255,255,255,0.15);'
    + '  --border-radius-sm: 4px;'
    + '  --border-radius-md: 8px;'
    + '  --border-radius-lg: 12px;'
    + '  --border-radius-pill: 999px;'
    + '  --color-success: #22c55e;'
    + '  --color-success-bg: rgba(34,197,94,0.15);'
    + '  --color-success-text: #86efac;'
    + '  --color-error: #ef4444;'
    + '  --color-error-bg: rgba(239,68,68,0.15);'
    + '  --color-error-text: #fca5a5;'
    + '  --color-warning: #eab308;'
    + '  --color-warning-bg: rgba(234,179,8,0.15);'
    + '  --color-warning-text: #fde047;'
    + '  --color-info: #3b82f6;'
    + '  --color-info-bg: rgba(59,130,246,0.15);'
    + '  --color-info-text: #93bbfd;'
    + '  --decision-proposed: #3b82f6;'
    + '  --decision-proposed-bg: rgba(59,130,246,0.15);'
    + '  --decision-proposed-text: #93bbfd;'
    + '  --decision-approved: #22c55e;'
    + '  --decision-approved-bg: rgba(34,197,94,0.15);'
    + '  --decision-approved-text: #86efac;'
    + '  --decision-superseded: #6b7280;'
    + '  --decision-superseded-bg: rgba(107,114,128,0.15);'
    + '  --decision-superseded-text: #9ca3af;'
    + '  --entity-decision: #818cf8;'
    + '  --entity-decision-bg: rgba(129,140,248,0.15);'
    + '  --entity-bridge: #a78bfa;'
    + '  --entity-bridge-bg: rgba(167,139,250,0.15);'
    + '  --entity-task: #2dd4bf;'
    + '  --entity-task-bg: rgba(45,212,191,0.15);'
    + '  --entity-project: #60a5fa;'
    + '  --entity-project-bg: rgba(96,165,250,0.15);'
    + '  --priority-high: #ef4444;'
    + '  --priority-high-bg: rgba(239,68,68,0.15);'
    + '  --priority-high-text: #fca5a5;'
    + '  --priority-medium: #f59e0b;'
    + '  --priority-medium-bg: rgba(245,158,11,0.15);'
    + '  --priority-medium-text: #fcd34d;'
    + '  --priority-low: #22c55e;'
    + '  --priority-low-bg: rgba(34,197,94,0.15);'
    + '  --priority-low-text: #86efac;'
    + '  --font-sans: \'Figtree\',-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;'
    + '  --font-mono: \'SF Mono\',\'Fira Code\',\'Cascadia Code\',monospace;'
    + '  --text-h1: 24px;'
    + '  --text-h2: 20px;'
    + '  --text-h3: 16px;'
    + '  --text-body: 14px;'
    + '  --text-small: 12px;'
    + '  --text-xs: 11px;'
    + '  --weight-regular: 400;'
    + '  --weight-medium: 500;'
    + '  --weight-semibold: 600;'
    + '  --weight-bold: 700;'
    + '  --leading-tight: 1.3;'
    + '  --leading-normal: 1.6;'
    + '  --space-1: 4px;'
    + '  --space-2: 8px;'
    + '  --space-3: 12px;'
    + '  --space-4: 16px;'
    + '  --space-5: 20px;'
    + '  --space-6: 24px;'
    + '  --space-8: 32px;'
    + '  --transition-fast: 0.15s ease;'
    + '  --transition-normal: 0.25s ease;'
    + '  --scrollbar-thumb: rgba(255,255,255,0.12);'
    + '  --scrollbar-thumb-hover: rgba(255,255,255,0.2);'
    + '}'
    + ''
    + '@media (prefers-color-scheme: light) {'
    + '  :root {'
    + '    --glass-bg: rgba(255,255,255,0.7);'
    + '    --glass-bg-heavy: rgba(255,255,255,0.85);'
    + '    --glass-border: rgba(0,0,0,0.08);'
    + '    --glass-shadow: 0 8px 32px rgba(0,0,0,0.08);'
    + '    --glass-shadow-elevated: 0 12px 40px rgba(0,0,0,0.12);'
    + '    --glass-inset-highlight: inset 0 1px 0 rgba(255,255,255,0.5);'
    + '    --bg-app: #f5f5f7;'
    + '    --bg-surface: rgba(255,255,255,0.8);'
    + '    --bg-surface-hover: rgba(255,255,255,0.95);'
    + '    --bg-surface-subtle: rgba(255,255,255,0.5);'
    + '    --text-primary: rgba(0,0,0,0.87);'
    + '    --text-secondary: rgba(0,0,0,0.6);'
    + '    --text-tertiary: rgba(0,0,0,0.38);'
    + '    --accent-primary: #6366f1;'
    + '    --accent-primary-hover: #4f46e5;'
    + '    --accent-primary-ghost: rgba(99,102,241,0.1);'
    + '    --border-default: rgba(0,0,0,0.08);'
    + '    --border-subtle: rgba(0,0,0,0.04);'
    + '    --border-strong: rgba(0,0,0,0.15);'
    + '    --color-success-text: #16a34a;'
    + '    --color-error-text: #dc2626;'
    + '    --color-warning-text: #ca8a04;'
    + '    --color-info-text: #2563eb;'
    + '    --decision-proposed-text: #2563eb;'
    + '    --decision-approved-text: #16a34a;'
    + '    --decision-superseded-text: #4b5563;'
    + '    --priority-high-text: #dc2626;'
    + '    --priority-medium-text: #ca8a04;'
    + '    --priority-low-text: #16a34a;'
    + '    --scrollbar-thumb: rgba(0,0,0,0.15);'
    + '    --scrollbar-thumb-hover: rgba(0,0,0,0.25);'
    + '  }'
    + '}'
    + ''
    + '.decidr-badge {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  padding: 2px 8px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  font-size: var(--text-xs);'
    + '  font-weight: var(--weight-medium);'
    + '  line-height: var(--leading-tight);'
    + '}'
    + ''
    + '@keyframes decidr-stagger-fade-in {'
    + '  from { opacity: 0; transform: translateY(8px); }'
    + '  to { opacity: 1; transform: translateY(0); }'
    + '}'
    + ''
    + '.decidr-stats-row {'
    + '  display: grid;'
    + '  grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));'
    + '  gap: var(--space-3);'
    + '  margin-bottom: var(--space-5);'
    + '}'
    + ''
    + '.decidr-stat-card {'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-lg);'
    + '  padding: var(--space-3);'
    + '  text-align: center;'
    + '  box-shadow: var(--glass-shadow), var(--glass-inset-highlight);'
    + '  animation: decidr-stagger-fade-in 0.4s ease both;'
    + '}'
    + ''
    + '.decidr-stat-value {'
    + '  font-size: var(--text-h1);'
    + '  font-weight: var(--weight-bold);'
    + '  color: var(--accent-primary);'
    + '  line-height: 1.1;'
    + '}'
    + ''
    + '.decidr-stat-label {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-secondary);'
    + '  font-weight: var(--weight-medium);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '  margin-top: var(--space-1);'
    + '}'
    + ''
    + '.decidr-section-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-2);'
    + '  font-size: var(--text-h3);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '  margin-bottom: var(--space-4);'
    + '}'
    + '.decidr-section-icon {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  color: var(--text-tertiary);'
    + '}'
    + '.decidr-section-icon svg {'
    + '  width: 18px;'
    + '  height: 18px;'
    + '}'
    + '.decidr-section-count {'
    + '  font-weight: var(--weight-normal);'
    + '  color: var(--text-tertiary);'
    + '  font-size: var(--text-body);'
    + '}'
    + ''
    + '.decidr-card {'
    + '  display: flex;'
    + '  align-items: flex-start;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-2) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '  animation: decidr-stagger-fade-in 0.3s ease both;'
    + '}'
    + '.decidr-card:hover {'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-card-icon {'
    + '  width: 24px;'
    + '  height: 24px;'
    + '  flex-shrink: 0;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  color: var(--text-secondary);'
    + '  margin-top: 1px;'
    + '}'
    + '.decidr-card-icon svg {'
    + '  width: 20px;'
    + '  height: 20px;'
    + '}'
    + '.decidr-card-body {'
    + '  flex: 1;'
    + '  min-width: 0;'
    + '}'
    + '.decidr-card-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  margin-bottom: 4px;'
    + '}'
    + '.decidr-card-type-label {'
    + '  font-size: 13px;'
    + '  font-weight: 600;'
    + '  color: var(--text-secondary);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '}'
    + '.decidr-card-title {'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '}'
    + '.decidr-card-desc {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-card-meta {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-card-stat {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-card-date {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-card-connection {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-progress-wrap {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-2);'
    + '  margin-top: 4px;'
    + '}'
    + '.decidr-progress-bar {'
    + '  flex: 1;'
    + '  height: 4px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--bg-surface);'
    + '  overflow: hidden;'
    + '}'
    + '.decidr-progress-fill {'
    + '  height: 100%;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--accent-primary);'
    + '  transition: width 0.3s ease;'
    + '}'
    + '.decidr-progress-fill-done {'
    + '  background: var(--color-success);'
    + '}'
    + '.decidr-progress-label {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  white-space: nowrap;'
    + '}'
    + ''
    + '.decidr-status-open {'
    + '  background: var(--decision-proposed-bg);'
    + '  color: var(--decision-proposed-text);'
    + '}'
    + '.decidr-status-in_progress {'
    + '  background: var(--color-info-bg);'
    + '  color: var(--color-info-text);'
    + '}'
    + '.decidr-status-decided {'
    + '  background: var(--decision-approved-bg);'
    + '  color: var(--decision-approved-text);'
    + '}'
    + '.decidr-status-deferred {'
    + '  background: var(--color-warning-bg);'
    + '  color: var(--color-warning-text);'
    + '}'
    + '.decidr-status-todo {'
    + '  background: var(--bg-surface);'
    + '  color: var(--text-secondary);'
    + '}'
    + '.decidr-status-done {'
    + '  background: var(--color-success-bg);'
    + '  color: var(--color-success-text);'
    + '}'
    + '.decidr-status-proposed {'
    + '  background: var(--decision-proposed-bg);'
    + '  color: var(--decision-proposed-text);'
    + '}'
    + '.decidr-status-under_discussion {'
    + '  background: var(--color-info-bg);'
    + '  color: var(--color-info-text);'
    + '}'
    + '.decidr-status-agreed {'
    + '  background: var(--decision-approved-bg);'
    + '  color: var(--decision-approved-text);'
    + '}'
    + '.decidr-status-implemented {'
    + '  background: var(--color-success-bg);'
    + '  color: var(--color-success-text);'
    + '}'
    + '.decidr-status-planning {'
    + '  background: var(--color-warning-bg);'
    + '  color: var(--color-warning-text);'
    + '}'
    + '.decidr-status-on_hold {'
    + '  background: var(--color-warning-bg);'
    + '  color: var(--color-warning-text);'
    + '}'
    + '.decidr-status-archived {'
    + '  background: var(--decision-superseded-bg);'
    + '  color: var(--decision-superseded-text);'
    + '}'
    + '.decidr-status-approved {'
    + '  background: var(--decision-approved-bg);'
    + '  color: var(--decision-approved-text);'
    + '}'
    + '.decidr-status-active {'
    + '  background: var(--color-success-bg);'
    + '  color: var(--color-success-text);'
    + '}'
    + '.decidr-status-completed {'
    + '  background: var(--color-success-bg);'
    + '  color: var(--color-success-text);'
    + '}'
    + '.decidr-status-superseded {'
    + '  background: var(--decision-superseded-bg);'
    + '  color: var(--decision-superseded-text);'
    + '}'
    + '.decidr-status-blocked {'
    + '  background: var(--color-error-bg);'
    + '  color: var(--color-error-text);'
    + '}'
    + '.decidr-status-pending {'
    + '  background: var(--color-warning-bg);'
    + '  color: var(--color-warning-text);'
    + '}'
    + '.decidr-status-draft {'
    + '  background: var(--bg-surface);'
    + '  color: var(--text-secondary);'
    + '}'
    + ''
    + '.decidr-priority-high {'
    + '  background: var(--priority-high-bg);'
    + '  color: var(--priority-high-text);'
    + '}'
    + '.decidr-priority-medium {'
    + '  background: var(--priority-medium-bg);'
    + '  color: var(--priority-medium-text);'
    + '}'
    + '.decidr-priority-low {'
    + '  background: var(--priority-low-bg);'
    + '  color: var(--priority-low-text);'
    + '}'
    + ''
    + '.decidr-entity-decision {'
    + '  background: var(--entity-decision-bg);'
    + '  color: var(--entity-decision);'
    + '}'
    + '.decidr-entity-bridge {'
    + '  background: var(--entity-bridge-bg);'
    + '  color: var(--entity-bridge);'
    + '}'
    + '.decidr-entity-task {'
    + '  background: var(--entity-task-bg);'
    + '  color: var(--entity-task);'
    + '}'
    + '.decidr-entity-project {'
    + '  background: var(--entity-project-bg);'
    + '  color: var(--entity-project);'
    + '}'
    + ''
    + '.decidr-health-bar {'
    + '  height: 6px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--bg-surface);'
    + '  overflow: hidden;'
    + '  display: flex;'
    + '}'
    + '.decidr-health-segment {'
    + '  height: 100%;'
    + '  transition: width 0.3s ease;'
    + '}'
    + ''
    + '.decidr-so-overlay {'
    + '  position: absolute;'
    + '  inset: 0;'
    + '  background: rgba(0,0,0,0.4);'
    + '  backdrop-filter: blur(2px);'
    + '  -webkit-backdrop-filter: blur(2px);'
    + '  z-index: 1000;'
    + '  opacity: 0;'
    + '  pointer-events: none;'
    + '  transition: opacity var(--transition-normal);'
    + '}'
    + '.decidr-so-overlay.decidr-so-open {'
    + '  opacity: 1;'
    + '  pointer-events: auto;'
    + '}'
    + '.decidr-so-panel {'
    + '  position: absolute;'
    + '  top: 0;'
    + '  right: 0;'
    + '  bottom: 0;'
    + '  width: clamp(320px, 520px, 90vw);'
    + '  background: var(--bg-app, var(--glass-bg-heavy));'
    + '  border-left: 1px solid var(--glass-border);'
    + '  box-shadow: -8px 0 32px rgba(0,0,0,0.3);'
    + '  z-index: 1001;'
    + '  display: flex;'
    + '  flex-direction: column;'
    + '  transform: translateX(100%);'
    + '  transition: transform 0.3s cubic-bezier(0.16,1,0.3,1);'
    + '}'
    + '.decidr-so-panel.decidr-so-open {'
    + '  transform: translateX(0);'
    + '}'
    + '.decidr-so-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-2);'
    + '  padding: var(--space-3) var(--space-4);'
    + '  border-bottom: 1px solid var(--glass-border);'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-so-content {'
    + '  position: relative;'
    + '  flex: 1;'
    + '  overflow-y: auto;'
    + '  padding: var(--space-4);'
    + '  scrollbar-width: thin;'
    + '  scrollbar-color: var(--scrollbar-thumb) transparent;'
    + '}'
    + '.decidr-so-content::-webkit-scrollbar { width: 8px; }'
    + '.decidr-so-content::-webkit-scrollbar-track { background: transparent; }'
    + '.decidr-so-content::-webkit-scrollbar-thumb {'
    + '  background: var(--scrollbar-thumb);'
    + '  border-radius: 4px;'
    + '  border: 2px solid transparent;'
    + '  background-clip: padding-box;'
    + '}'
    + '.decidr-so-content::-webkit-scrollbar-thumb:hover {'
    + '  background: var(--scrollbar-thumb-hover);'
    + '  background-clip: padding-box;'
    + '}'
    + '.decidr-so-header-row {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 12px;'
    + '}'
    + '.decidr-so-btn-back {'
    + '  background: none;'
    + '  border: none;'
    + '  cursor: pointer;'
    + '  color: inherit;'
    + '  padding: 4px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  display: flex;'
    + '  align-items: center;'
    + '  opacity: 0.7;'
    + '}'
    + '.decidr-so-btn-back:hover {'
    + '  opacity: 1;'
    + '  background: var(--bg-surface-hover);'
    + '}'
    + '.decidr-so-type-badge {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  font-size: 10px;'
    + '  font-weight: 600;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.05em;'
    + '  padding: 3px 8px;'
    + '  border-radius: 4px;'
    + '  white-space: nowrap;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-so-type-decision { color: var(--entity-decision); background: var(--entity-decision-bg); }'
    + '.decidr-so-type-project { color: var(--entity-project); background: var(--entity-project-bg); }'
    + '.decidr-so-type-bridge { color: var(--entity-bridge); background: var(--entity-bridge-bg); }'
    + '.decidr-so-type-task { color: var(--entity-task); background: var(--entity-task-bg); }'
    + '.decidr-so-type-initiative { color: var(--text-secondary); background: var(--bg-surface); }'
    + '.decidr-so-title {'
    + '  flex: 1;'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-semibold);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '  min-width: 0;'
    + '}'
    + '.decidr-so-detail {'
    + '  display: flex;'
    + '  flex-direction: column;'
    + '  gap: var(--space-3);'
    + '}'
    + '.decidr-so-detail-title {'
    + '  font-size: var(--text-h3);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '  margin: 0 0 var(--space-2) 0;'
    + '}'
    + '.decidr-so-meta {'
    + '  display: flex;'
    + '  flex-wrap: wrap;'
    + '  gap: 8px 16px;'
    + '  margin-bottom: var(--space-4);'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-secondary);'
    + '}'
    + '.decidr-so-meta-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '}'
    + '.decidr-so-description {'
    + '  font-size: var(--text-small);'
    + '  line-height: 1.6;'
    + '  color: var(--text-secondary);'
    + '  margin-bottom: var(--space-4);'
    + '}'
    + '.decidr-so-section-title {'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-secondary);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + '.decidr-so-list {'
    + '  display: flex;'
    + '  flex-direction: column;'
    + '  margin-bottom: var(--space-4);'
    + '}'
    + '.decidr-so-list-item {'
    + '  padding: 10px 12px;'
    + '  border-radius: var(--border-radius-md);'
    + '  background: var(--bg-surface-subtle);'
    + '  margin-bottom: 6px;'
    + '  cursor: pointer;'
    + '  transition: background 0.15s ease;'
    + '}'
    + '.decidr-so-list-item:hover {'
    + '  background: var(--bg-surface-hover);'
    + '}'
    + '.decidr-so-list-title {'
    + '  flex: 1;'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-primary);'
    + '}'
    + '.decidr-so-decision-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-2) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: var(--space-1);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '}'
    + '.decidr-so-decision-item:hover {'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-so-decision-title {'
    + '  flex: 1;'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '}'
    + '.decidr-so-decision-chevron {'
    + '  color: var(--text-tertiary);'
    + '  font-size: 18px;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-so-supersedes-badge {'
    + '  font-size: 10px;'
    + '  font-weight: var(--weight-semibold);'
    + '  padding: 2px 6px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  background: rgba(234, 179, 8, 0.15);'
    + '  color: #fde047;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.03em;'
    + '  white-space: nowrap;'
    + '}'
    + '.decidr-so-decision-superseded {'
    + '  margin-left: 24px;'
    + '  border-left: 2px solid var(--text-tertiary);'
    + '  padding-left: 12px;'
    + '  opacity: 0.6;'
    + '}'
    + '.decidr-so-decision-superseded .decidr-so-decision-title {'
    + '  text-decoration: line-through;'
    + '}'
    + '.decidr-so-decision-superseded-indicator {'
    + '  font-size: 12px;'
    + '  color: var(--text-tertiary);'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-so-decision-superseded-label {'
    + '  font-size: 11px;'
    + '  color: var(--text-tertiary);'
    + '  font-weight: var(--weight-semibold);'
    + '}'
    + '.decidr-so-decision-was-status {'
    + '  font-size: 10px;'
    + '  color: var(--text-tertiary);'
    + '  font-style: italic;'
    + '}'
    + '.decidr-so-decision-body {'
    + '  flex: 1;'
    + '  min-width: 0;'
    + '}'
    + '.decidr-so-task-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-2) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: var(--space-1);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '}'
    + '.decidr-so-task-item:hover {'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-so-task-checkbox {'
    + '  width: 20px;'
    + '  height: 20px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  border: 2px solid var(--border-strong);'
    + '  background: transparent;'
    + '  color: transparent;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  flex-shrink: 0;'
    + '  cursor: pointer;'
    + '  font-size: 12px;'
    + '  font-weight: bold;'
    + '  transition: all var(--transition-fast);'
    + '  padding: 0;'
    + '}'
    + '.decidr-so-task-checkbox:hover {'
    + '  border-color: var(--color-success);'
    + '}'
    + '.decidr-so-task-checkbox.checked {'
    + '  background: var(--color-success);'
    + '  border-color: var(--color-success);'
    + '  color: white;'
    + '}'
    + '.decidr-so-task-title {'
    + '  flex: 1;'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '}'
    + '.decidr-so-task-done .decidr-so-task-title {'
    + '  text-decoration: line-through;'
    + '  color: var(--text-tertiary);'
    + '}'
    + '.decidr-so-field {'
    + '  display: flex;'
    + '  align-items: baseline;'
    + '  gap: var(--space-3);'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + '.decidr-so-field-label {'
    + '  color: var(--text-tertiary);'
    + '  font-size: var(--text-small);'
    + '  flex-shrink: 0;'
    + '  min-width: 80px;'
    + '}'
    + '.decidr-so-field-value {'
    + '  color: var(--text-primary);'
    + '  font-weight: var(--weight-medium);'
    + '}'
    + ''
    + '@keyframes decidr-spin {'
    + '  to { transform: rotate(360deg); }'
    + '}'
    + '.decidr-spinner {'
    + '  width: 20px;'
    + '  height: 20px;'
    + '  border: 2px solid var(--border-default);'
    + '  border-top-color: var(--accent-primary);'
    + '  border-radius: 50%;'
    + '  animation: decidr-spin 0.6s linear infinite;'
    + '}'
    + ''
    + '/* ─── Frosted Glass Loading Pane ─── */'
    + '@keyframes decidr-glow-tl {'
    + '  0% { opacity: 0.30; }'
    + '  25% { opacity: 0.15; }'
    + '  50% { opacity: 0.06; }'
    + '  75% { opacity: 0.15; }'
    + '  100% { opacity: 0.30; }'
    + '}'
    + '@keyframes decidr-glow-br {'
    + '  0% { opacity: 0.06; }'
    + '  25% { opacity: 0.15; }'
    + '  50% { opacity: 0.30; }'
    + '  75% { opacity: 0.15; }'
    + '  100% { opacity: 0.06; }'
    + '}'
    + '@keyframes decidr-glass-text-pulse {'
    + '  0%, 100% { opacity: 0.4; }'
    + '  50% { opacity: 0.9; }'
    + '}'
    + '.decidr-glass-pane {'
    + '  position: absolute;'
    + '  inset: 0;'
    + '  overflow: hidden;'
    + '  z-index: 5;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '}'
    + '.decidr-glass-glow-tl {'
    + '  position: absolute;'
    + '  inset: 0;'
    + '  background: linear-gradient(135deg, rgba(100,160,255,0.4) 0%, rgba(100,160,255,0.15) 35%, rgba(150,140,255,0.08) 50%, transparent 75%);'
    + '  animation: decidr-glow-tl 4s ease-in-out infinite;'
    + '  pointer-events: none;'
    + '}'
    + '.decidr-glass-glow-br {'
    + '  position: absolute;'
    + '  inset: 0;'
    + '  background: linear-gradient(315deg, rgba(200,120,255,0.4) 0%, rgba(200,120,255,0.15) 35%, rgba(150,140,255,0.08) 50%, transparent 75%);'
    + '  animation: decidr-glow-br 4s ease-in-out infinite;'
    + '  pointer-events: none;'
    + '}'
    + '.decidr-glass-loader-text {'
    + '  position: relative;'
    + '  z-index: 1;'
    + '  color: var(--text-tertiary);'
    + '  font-size: var(--text-small, 13px);'
    + '  font-weight: var(--weight-medium, 500);'
    + '  letter-spacing: 0.06em;'
    + '  text-transform: uppercase;'
    + '  animation: decidr-glass-text-pulse 4s ease-in-out infinite;'
    + '}'
    + '.decidr-glass-pane-enriching {'
    + '  z-index: 2;'
    + '}'
    + ''
    + '.decidr-scroll {'
    + '  scrollbar-width: thin;'
    + '  scrollbar-color: var(--scrollbar-thumb) transparent;'
    + '}'
    + '.decidr-scroll::-webkit-scrollbar {'
    + '  width: 6px;'
    + '}'
    + '.decidr-scroll::-webkit-scrollbar-track {'
    + '  background: transparent;'
    + '}'
    + '.decidr-scroll::-webkit-scrollbar-thumb {'
    + '  background: var(--scrollbar-thumb);'
    + '  border-radius: var(--border-radius-pill);'
    + '}'
    + '.decidr-scroll::-webkit-scrollbar-thumb:hover {'
    + '  background: var(--scrollbar-thumb-hover);'
    + '}'
    + '.decidr-next-step-item + .decidr-next-step-item {'
    + '  margin-top: var(--space-2);'
    + '}'
    + '.decidr-next-step-item {'
    + '  display: flex;'
    + '  align-items: flex-start;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-3) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '  animation: decidr-stagger-fade-in 0.3s ease both;'
    + '}'
    + '.decidr-next-step-item:hover {'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-next-step-icon {'
    + '  width: 24px;'
    + '  height: 24px;'
    + '  flex-shrink: 0;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  color: var(--text-secondary);'
    + '  margin-top: 1px;'
    + '}'
    + '.decidr-next-step-icon svg {'
    + '  width: 20px;'
    + '  height: 20px;'
    + '}'
    + '.decidr-next-step-body {'
    + '  flex: 1;'
    + '  min-width: 0;'
    + '}'
    + '.decidr-next-step-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  margin-bottom: 4px;'
    + '}'
    + '.decidr-next-step-type-label {'
    + '  font-size: 13px;'
    + '  font-weight: 600;'
    + '  color: var(--text-secondary);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '}'
    + '.decidr-next-step-title {'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '}'
    + '.decidr-next-step-action-badge {'
    + '  display: inline-block;'
    + '  padding: 3px 10px;'
    + '  border-radius: 999px;'
    + '  font-size: 11px;'
    + '  font-weight: 600;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '}'
    + '.decidr-next-step-action-badge.decidr-action-review { background: rgba(245,158,11,0.15); color: #f59e0b; }'
    + '.decidr-next-step-action-badge.decidr-action-followup { background: rgba(239,68,68,0.15); color: #ef4444; }'
    + '.decidr-next-step-action-badge.decidr-action-tasks { background: rgba(59,130,246,0.15); color: #60a5fa; }'
    + '.decidr-next-step-action-badge.decidr-action-blocked { background: rgba(239,68,68,0.15); color: #ef4444; }'
    + '.decidr-next-step-action-badge.decidr-action-deferred { background: rgba(107,114,128,0.15); color: #9ca3af; }'
    + '.decidr-next-step-action-badge.decidr-action-progress { background: rgba(59,130,246,0.15); color: #60a5fa; }'
    + '@keyframes decidr-skeleton-pulse {'
    + '  0%, 100% { opacity: 0.15; }'
    + '  50% { opacity: 0.25; }'
    + '}'
    + '.decidr-skeleton .decidr-skeleton-box {'
    + '  background: var(--text-tertiary);'
    + '  animation: decidr-skeleton-pulse 1.5s ease-in-out infinite;'
    + '}'
    + '.decidr-next-step-meta {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-next-step-activity {'
    + '  font-size: 10px;'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-activity-label {'
    + '  font-weight: 600;'
    + '  font-size: 10px;'
    + '}'
    + '.decidr-activity-time {'
    + '  color: var(--text-tertiary);'
    + '  font-size: 10px;'
    + '}'
    + '.decidr-activity-commented { color: #3b82f6; }'
    + '.decidr-activity-status-changed { color: #f59e0b; }'
    + '.decidr-activity-updated, .decidr-activity-created { color: #22c55e; }'
    + '.decidr-activity-linked { color: #8b5cf6; }'
    + '.decidr-activity-unlinked { color: #ef4444; }'
    + '.decidr-activity-archived { color: #6b7280; }'
    + '.decidr-activity-restored { color: #06b6d4; }'
    + '.decidr-next-steps-group {'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  overflow: hidden;'
    + '  transition: border-color var(--transition-fast);'
    + '}'
    + '.decidr-next-steps-group:hover {'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-next-steps-group + .decidr-next-steps-group {'
    + '  margin-top: var(--space-2);'
    + '}'
    + '.decidr-next-steps-group-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  width: 100%;'
    + '  background: none;'
    + '  border: none;'
    + '  padding: var(--space-3) var(--space-4);'
    + '  cursor: pointer;'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-body);'
    + '  font-family: inherit;'
    + '  transition: background var(--transition-fast);'
    + '}'
    + '.decidr-next-steps-group-header:hover {'
    + '  background: rgba(255,255,255,0.03);'
    + '}'
    + '.decidr-next-steps-group-chevron {'
    + '  color: var(--text-tertiary);'
    + '  margin-right: var(--space-3);'
    + '  font-size: 10px;'
    + '  transition: transform var(--transition-fast);'
    + '  display: inline-flex;'
    + '  width: 12px;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-next-steps-group-label {'
    + '  font-weight: var(--weight-semibold);'
    + '  flex: 1;'
    + '  text-align: left;'
    + '}'
    + '.decidr-next-steps-group-count {'
    + '  font-weight: var(--weight-normal);'
    + '  color: var(--text-tertiary);'
    + '  font-size: var(--text-body);'
    + '  background: rgba(255,255,255,0.06);'
    + '  padding: 2px 10px;'
    + '  border-radius: 999px;'
    + '  font-size: var(--text-xs);'
    + '  font-weight: var(--weight-medium);'
    + '}'
    + '.decidr-next-steps-group-items {'
    + '  padding: 0 var(--space-3) var(--space-3);'
    + '}'
    + '.decidr-next-steps-group-statuses {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  margin-right: var(--space-3);'
    + '  flex-wrap: wrap;'
    + '}'
    + '.decidr-next-steps-group-statuses .decidr-badge {'
    + '  font-size: 10px;'
    + '  padding: 1px 8px;'
    + '}'
    + ''
    + '/* SlideOut enriched detail styles */'
    + '.decidr-so-parent-link {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  padding: 8px 12px;'
    + '  background: var(--bg-surface-subtle);'
    + '  border-radius: var(--border-radius-md);'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-secondary);'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + '.decidr-so-parent-icon { display: flex; align-items: center; }'
    + '.decidr-so-parent-icon svg { width: 14px; height: 14px; }'
    + '.decidr-so-parent-label { color: var(--text-tertiary); }'
    + '.decidr-so-nav-link {'
    + '  color: var(--accent-primary);'
    + '  cursor: pointer;'
    + '  text-decoration: none;'
    + '}'
    + '.decidr-so-nav-link:hover { text-decoration: underline; }'
    + ''
    + '.decidr-so-section { margin-bottom: var(--space-4); }'
    + '.decidr-so-section-count { font-weight: var(--weight-regular); color: var(--text-tertiary); }'
    + '.decidr-so-empty-hint { font-size: var(--text-small); color: var(--text-tertiary); padding: var(--space-2) 0; }'
    + ''
    + '/* Document items — matches task-item style */'
    + '.decidr-so-doc-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 8px 12px;'
    + '  background: var(--bg-surface-subtle);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: 4px;'
    + '  cursor: pointer;'
    + '  transition: background var(--transition-fast);'
    + '}'
    + '.decidr-so-doc-item:hover { background: var(--bg-surface-hover); }'
    + '.decidr-so-doc-link {'
    + '  flex: 1;'
    + '  min-width: 0;'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-primary);'
    + '  text-decoration: none;'
    + '  cursor: pointer;'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '}'
    + '.decidr-so-doc-link:hover { color: var(--text-link); }'
    + '.decidr-so-doc-link svg { flex-shrink: 0; opacity: 0.5; }'
    + '.decidr-so-doc-type-badge {'
    + '  font-size: 10px;'
    + '  padding: 1px 6px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  color: var(--text-tertiary);'
    + '  flex-shrink: 0;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.5px;'
    + '}'
    + '.decidr-so-btn-unlink-doc {'
    + '  background: none;'
    + '  border: none;'
    + '  cursor: pointer;'
    + '  color: var(--text-tertiary);'
    + '  padding: 2px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  flex-shrink: 0;'
    + '  opacity: 0;'
    + '  transition: opacity 0.15s, color 0.15s;'
    + '}'
    + '.decidr-so-doc-item:hover .decidr-so-btn-unlink-doc { opacity: 1; }'
    + '.decidr-so-btn-unlink-doc:hover { color: var(--color-error-text); }'
    + ''
    + '/* Progress bar */'
    + '.decidr-so-progress-wrap {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-2);'
    + '  margin-bottom: var(--space-4);'
    + '}'
    + '.decidr-so-progress-bar-inner {'
    + '  flex: 1;'
    + '  height: 6px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--bg-surface);'
    + '  overflow: hidden;'
    + '}'
    + '.decidr-so-progress-fill {'
    + '  height: 100%;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--accent-primary);'
    + '  transition: width 0.3s ease;'
    + '}'
    + '.decidr-so-progress-fill-done { background: var(--color-success); }'
    + '.decidr-so-progress-label {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '  white-space: nowrap;'
    + '}'
    + ''
    + '/* Timeline */'
    + '.decidr-so-timeline-filters {'
    + '  display: flex;'
    + '  gap: 6px;'
    + '  margin-bottom: var(--space-3);'
    + '  flex-wrap: wrap;'
    + '}'
    + '.decidr-so-timeline-chip {'
    + '  padding: 3px 10px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  border: 1px solid var(--border-default);'
    + '  background: transparent;'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-xs);'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-so-timeline-chip:hover { border-color: var(--accent-primary); color: var(--text-primary); }'
    + '.decidr-so-timeline-chip.active {'
    + '  background: var(--accent-primary-ghost);'
    + '  border-color: var(--accent-primary);'
    + '  color: var(--accent-primary);'
    + '}'
    + '.decidr-so-timeline-list { display: flex; flex-direction: column; }'
    + '.decidr-so-timeline-entry {'
    + '  display: flex;'
    + '  gap: 12px;'
    + '  padding: 12px 14px;'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: var(--space-1);'
    + '  cursor: pointer;'
    + '  transition: background 0.15s, border-color 0.15s;'
    + '}'
    + '.decidr-so-timeline-entry:hover { background: var(--bg-surface-hover); }'
    + '.decidr-so-timeline-icon {'
    + '  width: 24px;'
    + '  height: 24px;'
    + '  border-radius: 50%;'
    + '  border: 2px solid var(--border-default);'
    + '  background: var(--bg-surface);'
    + '  flex-shrink: 0;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-so-timeline-icon svg { width: 12px; height: 12px; color: var(--text-tertiary); display: block; }'
    + '.decidr-so-timeline-content { flex: 1; min-width: 0; }'
    + '.decidr-so-timeline-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  flex-wrap: wrap;'
    + '  margin-bottom: 4px;'
    + '}'
    + '.decidr-so-timeline-actor {'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '}'
    + '.decidr-so-timeline-action-pill {'
    + '  font-size: 10px;'
    + '  padding: 2px 8px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  font-weight: var(--weight-semibold);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.04em;'
    + '}'
    + '.decidr-so-timeline-time {'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-tertiary);'
    + '}'
    + '.decidr-so-timeline-desc {'
    + '  font-size: var(--text-body);'
    + '  color: var(--text-primary);'
    + '  line-height: 1.5;'
    + '}'
    + '.decidr-so-timeline-empty {'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-tertiary);'
    + '  padding: var(--space-2) 0;'
    + '}'
    + ''
    + '/* Timeline per-type icon styling */'
    + '.decidr-so-timeline-type-status .decidr-so-timeline-icon { border-color: #f59e0b; background: rgba(245, 158, 11, 0.15); }'
    + '.decidr-so-timeline-type-status .decidr-so-timeline-icon svg { color: #f59e0b; }'
    + '.decidr-so-timeline-type-status:hover { background: rgba(245, 158, 11, 0.08); }'
    + '.decidr-so-timeline-type-review .decidr-so-timeline-icon { border-color: #8b5cf6; background: rgba(139, 92, 246, 0.15); }'
    + '.decidr-so-timeline-type-review .decidr-so-timeline-icon svg { color: #8b5cf6; }'
    + '.decidr-so-timeline-type-review:hover { background: rgba(139, 92, 246, 0.08); }'
    + '.decidr-so-timeline-type-doc .decidr-so-timeline-icon { border-color: #3b82f6; background: rgba(59, 130, 246, 0.15); }'
    + '.decidr-so-timeline-type-doc .decidr-so-timeline-icon svg { color: #3b82f6; }'
    + '.decidr-so-timeline-type-doc:hover { background: rgba(59, 130, 246, 0.08); }'
    + '.decidr-so-timeline-type-task .decidr-so-timeline-icon { border-color: #10b981; background: rgba(16, 185, 129, 0.15); }'
    + '.decidr-so-timeline-type-task .decidr-so-timeline-icon svg { color: #10b981; }'
    + '.decidr-so-timeline-type-task:hover { background: rgba(16, 185, 129, 0.08); }'
    + '.decidr-so-timeline-type-comment .decidr-so-timeline-icon { border-color: #6366f1; background: rgba(99, 102, 241, 0.15); }'
    + '.decidr-so-timeline-type-comment .decidr-so-timeline-icon svg { color: #6366f1; }'
    + '.decidr-so-timeline-type-comment:hover { background: rgba(99, 102, 241, 0.08); }'
    + '.decidr-so-timeline-type-bridge .decidr-so-timeline-icon { border-color: #06b6d4; background: rgba(6, 182, 212, 0.15); }'
    + '.decidr-so-timeline-type-bridge .decidr-so-timeline-icon svg { color: #06b6d4; }'
    + '.decidr-so-timeline-type-bridge:hover { background: rgba(6, 182, 212, 0.08); }'
    + ''
    + '/* Timeline per-type pill styling */'
    + '.decidr-so-timeline-pill-status { background: rgba(245, 158, 11, 0.15); color: #f59e0b; }'
    + '.decidr-so-timeline-pill-review { background: rgba(139, 92, 246, 0.15); color: #8b5cf6; }'
    + '.decidr-so-timeline-pill-doc { background: rgba(59, 130, 246, 0.15); color: #3b82f6; }'
    + '.decidr-so-timeline-pill-task { background: rgba(16, 185, 129, 0.15); color: #10b981; }'
    + '.decidr-so-timeline-pill-comment { background: rgba(99, 102, 241, 0.15); color: #6366f1; }'
    + '.decidr-so-timeline-pill-bridge { background: rgba(6, 182, 212, 0.15); color: #06b6d4; }'
    + ''
    + '/* Timeline breadcrumb */'
    + '.decidr-so-timeline-breadcrumb { font-size: 12px; color: var(--text-secondary); line-height: 1.3; margin-top: 5px; }'
    + '.decidr-so-timeline-breadcrumb-sep { color: var(--text-tertiary); margin: 0 2px; }'
    + ''
    + '/* Supersession */'
    + '.decidr-so-superseded-banner {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 10px 12px;'
    + '  background: var(--color-warning-bg);'
    + '  border: 1px solid rgba(234,179,8,0.3);'
    + '  border-radius: var(--border-radius-md);'
    + '  font-size: var(--text-small);'
    + '  color: var(--color-warning-text);'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + '.decidr-so-superseded-icon { font-size: 16px; }'
    + '.decidr-so-supersedes-note {'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-secondary);'
    + '  padding: 4px 0;'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + ''
    + '/* Action bar */'
    + '.decidr-so-action-bar {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 8px 0;'
    + '  margin-bottom: var(--space-3);'
    + '  border-bottom: 1px solid var(--border-subtle);'
    + '  flex-wrap: wrap;'
    + '}'
    + '.decidr-so-btn {'
    + '  padding: 5px 12px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  border: 1px solid var(--border-default);'
    + '  background: transparent;'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-small);'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '}'
    + '.decidr-so-btn:hover { border-color: var(--accent-primary); color: var(--text-primary); }'
    + '.decidr-so-btn-primary {'
    + '  background: var(--accent-primary);'
    + '  border-color: var(--accent-primary);'
    + '  color: white;'
    + '}'
    + '.decidr-so-btn-primary:hover { background: var(--accent-primary-hover); }'
    + '.decidr-so-btn-danger { color: var(--color-error-text); }'
    + '.decidr-so-btn-danger:hover { border-color: var(--color-error); background: var(--color-error-bg); }'
    + '.decidr-so-btn-sm { padding: 3px 8px; font-size: var(--text-xs); }'
    + '.decidr-so-spacer { flex: 1; }'
    + '.decidr-so-btn svg { width: 14px; height: 14px; vertical-align: middle; }'
    + ''
    + '/* Status dropdown */'
    + '.decidr-so-status-dropdown {'
    + '  position: relative;'
    + '  display: inline-block;'
    + '}'
    + '.decidr-so-status-menu {'
    + '  position: absolute;'
    + '  top: 100%;'
    + '  left: 0;'
    + '  z-index: 10;'
    + '  min-width: 140px;'
    + '  background: var(--bg-app);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  box-shadow: var(--glass-shadow);'
    + '  padding: 4px;'
    + '  display: none;'
    + '}'
    + '.decidr-so-status-menu.open { display: block; }'
    + '.decidr-so-status-option {'
    + '  display: block;'
    + '  width: 100%;'
    + '  padding: 6px 10px;'
    + '  border: none;'
    + '  background: none;'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  cursor: pointer;'
    + '  border-radius: var(--border-radius-sm);'
    + '  text-align: left;'
    + '}'
    + '.decidr-so-status-option:hover { background: var(--bg-surface-hover); }'
    + ''
    + '/* Edit mode */'
    + '.decidr-so-edit-input {'
    + '  width: 100%;'
    + '  padding: 8px 10px;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-body);'
    + '  font-family: var(--font-sans);'
    + '  outline: none;'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + '.decidr-so-edit-input:focus { border-color: var(--accent-primary); }'
    + '.decidr-so-edit-textarea {'
    + '  width: 100%;'
    + '  padding: 8px 10px;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  font-family: var(--font-sans);'
    + '  outline: none;'
    + '  resize: vertical;'
    + '  min-height: 60px;'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + '.decidr-so-edit-textarea:focus { border-color: var(--accent-primary); }'
    + '.decidr-so-form-actions {'
    + '  display: flex;'
    + '  gap: 8px;'
    + '  justify-content: flex-end;'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + ''
    + '/* Inline forms (add task, link doc, comment) */'
    + '.decidr-so-inline-form {'
    + '  padding: 10px 12px;'
    + '  background: var(--bg-surface-subtle);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: var(--space-3);'
    + '  display: none;'
    + '}'
    + '.decidr-so-inline-form.visible { display: block; }'
    + '.decidr-so-inline-form input,'
    + '.decidr-so-inline-form textarea {'
    + '  width: 100%;'
    + '  padding: 6px 10px;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-sm);'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  font-family: var(--font-sans);'
    + '  outline: none;'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + '.decidr-so-inline-form input:focus,'
    + '.decidr-so-inline-form textarea:focus { border-color: var(--accent-primary); }'
    + ''
    + '/* Comment form */'
    + '.decidr-so-comment-form {'
    + '  margin-top: var(--space-4);'
    + '  padding-top: var(--space-3);'
    + '  border-top: 1px solid var(--border-subtle);'
    + '}'
    + '.decidr-so-comment-form textarea {'
    + '  width: 100%;'
    + '  padding: 8px 10px;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  font-family: var(--font-sans);'
    + '  outline: none;'
    + '  resize: vertical;'
    + '  min-height: 60px;'
    + '  margin-bottom: var(--space-2);'
    + '}'
    + '.decidr-so-comment-form textarea:focus { border-color: var(--accent-primary); }'
    + ''
    + '/* Task checkbox */'
    + '.decidr-so-task-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 8px 12px;'
    + '  background: var(--bg-surface-subtle);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: 4px;'
    + '  cursor: pointer;'
    + '  transition: background var(--transition-fast);'
    + '}'
    + '.decidr-so-task-item:hover { background: var(--bg-surface-hover); }'
    + '.decidr-so-task-checkbox {'
    + '  width: 16px;'
    + '  height: 16px;'
    + '  border: 2px solid var(--border-strong);'
    + '  border-radius: 3px;'
    + '  flex-shrink: 0;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-so-task-checkbox.checked {'
    + '  background: var(--color-success);'
    + '  border-color: var(--color-success);'
    + '}'
    + '.decidr-so-task-title { flex: 1; font-size: var(--text-small); color: var(--text-primary); }'
    + '.decidr-so-task-title.done { text-decoration: line-through; color: var(--text-tertiary); }'
    + ''
    + '/* Bridge items */'
    + '.decidr-so-bridge-item {'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  margin-bottom: 6px;'
    + '  overflow: hidden;'
    + '}'
    + '.decidr-so-bridge-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: space-between;'
    + '  padding: 8px 12px;'
    + '  cursor: pointer;'
    + '  transition: background var(--transition-fast);'
    + '}'
    + '.decidr-so-bridge-header:hover { background: var(--bg-surface-hover); }'
    + '.decidr-so-bridge-name { font-size: var(--text-small); color: var(--text-primary); }'
    + '.decidr-so-bridge-type { font-size: var(--text-xs); color: var(--text-tertiary); margin-left: 8px; }'
    + '.decidr-so-bridge-expand {'
    + '  max-height: 0;'
    + '  overflow: hidden;'
    + '  transition: max-height 0.25s ease;'
    + '}'
    + '.decidr-so-bridge-expand.open { max-height: 200px; }'
    + '.decidr-so-bridge-expand-inner {'
    + '  padding: 8px 12px;'
    + '  border-top: 1px solid var(--border-subtle);'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-secondary);'
    + '}'
    + ''
    + '/* Reviewers */'
    + '.decidr-so-reviewers {'
    + '  display: flex;'
    + '  flex-wrap: wrap;'
    + '  gap: 6px;'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + '.decidr-so-reviewer-chip {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  padding: 3px 8px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  background: var(--bg-surface);'
    + '  font-size: var(--text-xs);'
    + '  color: var(--text-secondary);'
    + '}'
    + '.decidr-so-reviewer-check { color: var(--color-success); font-weight: bold; }'
    + ''
    + '/* Color dots for projects */'
    + '.decidr-so-color-dot {'
    + '  width: 10px;'
    + '  height: 10px;'
    + '  border-radius: 50%;'
    + '  flex-shrink: 0;'
    + '}'
    + ''
    + '/* Loading placeholder for enrichment */'
    + '.decidr-so-loading-section {'
    + '  padding: var(--space-3) 0;'
    + '  color: var(--text-tertiary);'
    + '  font-size: var(--text-small);'
    + '  animation: decidr-glass-text-pulse 2.6s ease-in-out infinite;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '}'
    + '.decidr-so-loading-section .decidr-spinner { width: 14px; height: 14px; }'
    + ''
    + '/* Quick action buttons row */'
    + '.decidr-so-quick-actions {'
    + '  display: flex;'
    + '  gap: 8px;'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + ''
    + '/* Avatar + User Chip */'
    + '.decidr-avatar {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  color: white;'
    + '  font-weight: 600;'
    + '  border-radius: 50%;'
    + '}'
    + '.decidr-avatar-sm { width: 24px; height: 24px; font-size: 11px; }'
    + '.decidr-avatar-md { width: 32px; height: 32px; font-size: 13px; }'
    + '.decidr-avatar-lg { width: 40px; height: 40px; font-size: 15px; }'
    + '.decidr-user-chip {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  padding: 2px 10px 2px 2px;'
    + '  border-radius: 16px;'
    + '  background: var(--decidr-surface-2, rgba(255,255,255,0.06));'
    + '}'
    + '.decidr-user-chip-name { font-size: 13px; color: var(--decidr-text-primary, var(--text-primary)); }'
    + ''
    + '/* Blocker chips */'
    + '.decidr-so-blocker-chip {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  padding: 4px 10px;'
    + '  border-radius: 6px;'
    + '  font-size: 12px;'
    + '  border: 1px solid var(--decidr-border, var(--border-default));'
    + '  cursor: pointer;'
    + '  background: var(--decidr-surface-1, rgba(255,255,255,0.04));'
    + '}'
    + '.decidr-so-blocker-chip:hover { border-color: var(--decidr-accent, var(--accent-primary)); }'
    + '.decidr-so-blockers-list { display: flex; flex-wrap: wrap; gap: 6px; }'
    + ''
    + '/* Assign reviewer dropdown */'
    + '.decidr-so-reviewer-dropdown {'
    + '  position: absolute;'
    + '  top: 100%;'
    + '  left: 0;'
    + '  z-index: 100;'
    + '  min-width: 220px;'
    + '  background: var(--decidr-surface-3, rgba(30,30,40,0.95));'
    + '  border: 1px solid var(--decidr-border, var(--border-default));'
    + '  border-radius: 8px;'
    + '  padding: 8px 0;'
    + '  box-shadow: 0 8px 24px rgba(0,0,0,0.4);'
    + '  max-height: 240px;'
    + '  overflow-y: auto;'
    + '}'
    + '.decidr-so-reviewer-dropdown-header {'
    + '  padding: 6px 12px;'
    + '  font-size: 11px;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.05em;'
    + '  color: var(--decidr-text-secondary, var(--text-secondary));'
    + '  border-bottom: 1px solid var(--decidr-border, var(--border-default));'
    + '}'
    + '.decidr-so-reviewer-option {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 8px 12px;'
    + '  cursor: pointer;'
    + '  font-size: 13px;'
    + '  color: var(--decidr-text-primary, var(--text-primary));'
    + '}'
    + '.decidr-so-reviewer-option:hover { background: var(--decidr-surface-2, rgba(255,255,255,0.06)); }'
    + ''
    + '/* Approval entries */'
    + '.decidr-so-approval-entry { display: flex; align-items: center; gap: 8px; padding: 4px 0; }'
    + '.decidr-so-approval-date { font-size: 11px; color: var(--decidr-text-secondary, var(--text-secondary)); margin-left: auto; }'
    + ''
    + '/* Tab bar */'
    + '.decidr-so-tab-bar {'
    + '  display: flex;'
    + '  gap: 0;'
    + '  border-bottom: 1px solid var(--decidr-border, var(--border-default));'
    + '  margin-bottom: 12px;'
    + '}'
    + '.decidr-so-tab {'
    + '  padding: 8px 16px;'
    + '  font-size: 13px;'
    + '  color: var(--decidr-text-secondary, var(--text-secondary));'
    + '  cursor: pointer;'
    + '  border-bottom: 2px solid transparent;'
    + '  background: none;'
    + '  border-top: none;'
    + '  border-left: none;'
    + '  border-right: none;'
    + '  transition: color 0.15s, border-color 0.15s;'
    + '}'
    + '.decidr-so-tab:hover { color: var(--decidr-text-primary, var(--text-primary)); }'
    + '.decidr-so-tab.active { color: var(--decidr-accent, var(--accent-primary)); border-bottom-color: var(--decidr-accent, var(--accent-primary)); }'
    + '.decidr-so-tab-panel { display: none; }'
    + '.decidr-so-tab-panel.active { display: block; }'
    + ''
    + '/* Doc search items */'
    + '.decidr-so-doc-search-item {'
    + '  padding: 8px 12px;'
    + '  border-radius: 6px;'
    + '  cursor: pointer;'
    + '  font-size: 13px;'
    + '  color: var(--decidr-text-primary, var(--text-primary));'
    + '  border: 1px solid transparent;'
    + '}'
    + '.decidr-so-doc-search-item:hover { background: var(--decidr-surface-2, rgba(255,255,255,0.06)); }'
    + '.decidr-so-doc-search-item.selected { border-color: var(--decidr-accent, var(--accent-primary)); background: var(--decidr-surface-2, rgba(255,255,255,0.06)); }'
    + ''
    + '/* File input */'
    + '.decidr-so-file-input-wrap {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  padding: 8px 12px;'
    + '  border: 1px dashed var(--decidr-border, var(--border-default));'
    + '  border-radius: 8px;'
    + '  cursor: pointer;'
    + '  color: var(--decidr-text-secondary, var(--text-secondary));'
    + '  font-size: 13px;'
    + '}'
    + ''
    + '/* Tags */'
    + '.decidr-so-tags { display: flex; flex-wrap: wrap; gap: 6px; }'
    + ''
    + '/* Timeline breadcrumb */'
    + '.decidr-so-timeline-breadcrumb { font-size: 11px; color: var(--decidr-text-secondary, var(--text-secondary)); margin-bottom: 4px; }'

    + '/* Task cards (rich style for decision slide-out) */'
    + '.decidr-so-task-card {'
    + '  padding: 12px 14px;'
    + '  background: var(--bg-surface-subtle);'
    + '  border-radius: var(--border-radius-md);'
    + '  border-left: 3px solid var(--border-default);'
    + '  margin-bottom: var(--space-2);'
    + '  cursor: pointer;'
    + '  transition: background 0.15s;'
    + '}'
    + '.decidr-so-task-card:hover { background: var(--bg-surface-hover); }'
    + '.decidr-so-task-card-todo { border-left-color: var(--text-tertiary); }'
    + '.decidr-so-task-card-in-progress { border-left-color: var(--color-info, #f59e0b); }'
    + '.decidr-so-task-card-done { border-left-color: var(--color-success, #22c55e); }'
    + '.decidr-so-task-card-blocked { border-left-color: var(--color-danger, #ef4444); }'
    + '.decidr-so-task-card-header { margin-bottom: 4px; }'
    + '.decidr-so-task-card-title { font-size: var(--text-body); font-weight: var(--weight-medium); color: var(--text-primary); margin-bottom: 4px; }'
    + '.decidr-so-task-card-title.done { text-decoration: line-through; opacity: 0.6; }'
    + '.decidr-so-task-card-desc { font-size: var(--text-small); color: var(--text-secondary); margin-bottom: 4px; line-height: 1.4; }'
    + '.decidr-so-task-card-time { font-size: 11px; color: var(--text-tertiary); }'

    + '/* Reviewer card */'
    + '.decidr-so-reviewers-card {'
    + '  background: var(--bg-surface-subtle);'
    + '  border: 1px solid var(--border-default);'
    + '  border-radius: var(--border-radius-md);'
    + '  padding: 12px;'
    + '  margin-bottom: var(--space-3);'
    + '}'
    + '.decidr-so-reviewers-label {'
    + '  font-size: 11px;'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-tertiary);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.05em;'
    + '  margin-bottom: 8px;'
    + '}'
    + '.decidr-so-reviewer-chip {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  padding: 4px 10px 4px 4px;'
    + '  border-radius: 16px;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--border-default);'
    + '  font-size: 13px;'
    + '  color: var(--text-primary);'
    + '  transition: border-color 0.15s, background 0.15s;'
    + '}'
    + '.decidr-so-reviewer-chip.approved {'
    + '  border-color: var(--color-success, #22c55e);'
    + '  background: rgba(34, 197, 94, 0.08);'
    + '}'
    + '.decidr-so-reviewer-chip.rejected {'
    + '  border-color: var(--color-error, #ef4444);'
    + '  background: rgba(239, 68, 68, 0.08);'
    + '}'
    + '.decidr-so-reviewer-reject {'
    + '  color: var(--color-error, #ef4444);'
    + '  font-weight: 700;'
    + '  font-size: 13px;'
    + '}'
    + '.decidr-so-reviewers {'
    + '  display: flex;'
    + '  flex-wrap: wrap;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  margin-bottom: 8px;'
    + '}'
    + '.decidr-so-assign-btn {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  padding: 4px 12px;'
    + '  border: 1px dashed var(--border-default);'
    + '  border-radius: 16px;'
    + '  background: none;'
    + '  color: var(--text-secondary);'
    + '  font-size: 13px;'
    + '  cursor: pointer;'
    + '  transition: border-color 0.15s, color 0.15s;'
    + '}'
    + '.decidr-so-assign-btn:hover { border-color: var(--accent-primary); color: var(--accent-primary); }'
    + '.decidr-so-approval-progress { display: flex; align-items: center; gap: var(--space-3); margin-top: var(--space-3); padding: var(--space-2) var(--space-3); background: var(--bg-surface-subtle); border-radius: var(--border-radius-md); border: 1px solid var(--border-subtle); }'
    + '.decidr-so-approval-stepper { display: inline-flex; align-items: center; gap: var(--space-1); }'
    + '.decidr-so-stepper-btn { display: inline-flex; align-items: center; justify-content: center; width: 22px; height: 22px; padding: 0; border: 1px solid var(--border-default); border-radius: var(--border-radius-sm); background: var(--bg-surface); color: var(--text-secondary); font-size: var(--text-small); font-family: var(--font-sans); cursor: pointer; transition: all var(--transition-fast); line-height: 1; }'
    + '.decidr-so-stepper-btn:hover { background: var(--accent-primary-ghost); border-color: var(--accent-primary); color: var(--accent-primary); }'
    + '.decidr-so-stepper-label { font-size: var(--text-small); color: var(--text-secondary); font-weight: var(--weight-medium); min-width: 16px; text-align: center; }'
    + '.decidr-so-approval-divider { color: var(--text-tertiary); font-size: var(--text-small); }'
    + '.decidr-so-approval-count { font-size: var(--text-small); color: var(--text-secondary); }'
    + '.decidr-so-approval-satisfied { font-size: var(--text-small); color: var(--color-success-text); font-weight: var(--weight-semibold); }'
    + '.decidr-so-approval-actions { display: flex; gap: 8px; margin-top: 8px; }'
    + '.decidr-so-btn-approve { color: var(--color-success, #22c55e); border-color: var(--color-success, #22c55e); }'
    + '.decidr-so-btn-approve:hover { background: rgba(34, 197, 94, 0.1); }'
    + '.decidr-so-btn-reject { color: var(--color-error, #ef4444); border-color: var(--color-error, #ef4444); }'
    + '.decidr-so-btn-reject:hover { background: rgba(239, 68, 68, 0.1); }'
    + '.decidr-so-btn-active { background: rgba(255,255,255,0.06); cursor: default; opacity: 0.85; font-weight: 600; }'
    + '.decidr-so-btn-active:hover { background: rgba(255,255,255,0.06); }'
    + ''
    + '/* ─── Dashboard: Decision List Items ─── */'
    + '.decidr-decision-item + .decidr-decision-item { margin-top: var(--space-2); }'
    + '.decidr-decision-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-2) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '  animation: decidr-stagger-fade-in 0.3s ease both;'
    + '}'
    + '.decidr-decision-item:hover { border-color: var(--accent-primary); }'
    + '.decidr-decision-item-body { flex: 1; min-width: 0; }'
    + '.decidr-decision-item-title {'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '}'
    + '.decidr-decision-item-meta { font-size: var(--text-xs); color: var(--text-tertiary); margin-top: 2px; }'
    + '.decidr-decision-item-supersedes-badge {'
    + '  font-size: 10px;'
    + '  font-weight: var(--weight-semibold);'
    + '  padding: 2px 6px;'
    + '  border-radius: var(--border-radius-sm);'
    + '  background: rgba(234, 179, 8, 0.15);'
    + '  color: #fde047;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.03em;'
    + '  white-space: nowrap;'
    + '}'
    + '.decidr-decision-item-activity {'
    + '  font-size: 10px;'
    + '  margin-top: 2px;'
    + '}'
    + '.decidr-decision-item-superseded {'
    + '  margin-left: 24px;'
    + '  border-left: 2px solid var(--text-tertiary);'
    + '  padding-left: 12px;'
    + '  opacity: 0.6;'
    + '}'
    + '.decidr-decision-item-superseded .decidr-decision-item-title { text-decoration: line-through; }'
    + '.decidr-decision-item-superseded-indicator { font-size: 12px; color: var(--text-tertiary); flex-shrink: 0; }'
    + ''
    + '/* ─── Dashboard: Pending Items ─── */'
    + '.decidr-pending-item + .decidr-pending-item { margin-top: var(--space-2); }'
    + '.decidr-pending-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-2) var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast);'
    + '  animation: decidr-stagger-fade-in 0.3s ease both;'
    + '}'
    + '.decidr-pending-item:hover { border-color: var(--accent-primary); }'
    + '.decidr-pending-item-dot {'
    + '  width: 8px;'
    + '  height: 8px;'
    + '  border-radius: 50%;'
    + '  background: var(--color-warning);'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-pending-item-body { flex: 1; min-width: 0; }'
    + '.decidr-pending-item-title {'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '}'
    + '.decidr-pending-item-project { font-size: var(--text-xs); color: var(--text-tertiary); margin-top: 2px; }'
    + ''
    + '/* ─── Dashboard: Tab Bar ─── */'
    + '.decidr-dash-tab {'
    + '  padding: 6px 14px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  border: 1px solid var(--glass-border);'
    + '  background: transparent;'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-small);'
    + '  font-family: inherit;'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-dash-tab:hover { background: var(--glass-bg); color: var(--text-primary); }'
    + '.decidr-dash-tab.active {'
    + '  background: var(--glass-bg-heavy);'
    + '  color: var(--text-primary);'
    + '  border-color: var(--text-secondary);'
    + '}'
    + ''
    + '/* ─── Dashboard: Status Filter Pills ─── */'
    + '.decidr-dash-status-pill {'
    + '  padding: 4px 12px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  border: 1px solid var(--glass-border);'
    + '  background: var(--bg-surface);'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-small);'
    + '  font-family: inherit;'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-dash-status-pill:hover { background: var(--glass-bg-heavy); color: var(--text-primary); }'
    + '.decidr-dash-status-pill.active {'
    + '  background: var(--accent-primary);'
    + '  color: white;'
    + '  border-color: var(--accent-primary);'
    + '}'
    + ''
    + '/* ─── Dashboard: Enhanced Initiative Card ─── */'
    + '.decidr-init-header {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  cursor: pointer;'
    + '}'
    + '.decidr-init-toggle {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  flex-shrink: 0;'
    + '  color: var(--text-secondary);'
    + '  transition: color 0.2s ease;'
    + '}'
    + '.decidr-init-toggle svg { transition: transform 0.25s ease; }'
    + '.decidr-init-toggle:hover { color: var(--text-primary); }'
    + '.decidr-init-card-collapsed .decidr-init-toggle svg { transform: rotate(-90deg); }'
    + '.decidr-init-title-area { flex: 1; min-width: 200px; }'
    + '.decidr-init-name { font-size: var(--text-h3); font-weight: var(--weight-semibold); color: var(--text-primary); display: block; }'
    + '.decidr-init-description { font-size: var(--text-small); color: var(--text-secondary); display: block; margin-top: 2px; }'
    + '.decidr-init-stats { display: flex; align-items: center; gap: var(--space-3); }'
    + '.decidr-init-stat { font-size: var(--text-xs); color: var(--text-secondary); font-weight: var(--weight-medium); white-space: nowrap; }'
    + '.decidr-init-health { display: flex; align-items: center; gap: var(--space-3); min-width: 280px; flex-shrink: 0; }'
    + '.decidr-init-health .decidr-decision-health-legend { flex-shrink: 0; margin-top: 0; }'
    + '.decidr-init-health .decidr-decision-health { flex: 1; min-width: 100px; }'
    + ''
    + '/* ─── Dashboard: Decision Health Legend ─── */'
    + '.decidr-decision-health-legend { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }'
    + '.decidr-decision-health-legend-item {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  font-size: 11px;'
    + '  color: var(--text-secondary);'
    + '  white-space: nowrap;'
    + '}'
    + '.decidr-decision-health-legend-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }'
    + ''
    + '/* ─── Dashboard: Show More Button ─── */'
    + '.decidr-dash-show-more {'
    + '  display: block;'
    + '  width: 100%;'
    + '  padding: var(--space-2) 0;'
    + '  margin-top: var(--space-1);'
    + '  background: transparent;'
    + '  border: 1px dashed var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-small);'
    + '  font-family: inherit;'
    + '  cursor: pointer;'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-dash-show-more:hover { background: var(--glass-bg); color: var(--text-primary); }'
    + ''
    + '/* ─── Dashboard: Compact Project Card ─── */'
    + '.decidr-dash-proj {'
    + '  background: var(--glass-bg);'
    + '  backdrop-filter: blur(var(--glass-blur));'
    + '  -webkit-backdrop-filter: blur(var(--glass-blur));'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-lg);'
    + '  padding: var(--space-3);'
    + '  cursor: pointer;'
    + '  transition: border-color var(--transition-fast), transform var(--transition-fast);'
    + '  animation: decidr-stagger-fade-in 0.4s ease both;'
    + '}'
    + '.decidr-dash-proj:hover { border-color: var(--accent-primary-subtle); transform: translateY(-1px); }'
    + '.decidr-dash-proj-name {'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '  margin-bottom: 4px;'
    + '}'
    + '.decidr-dash-proj-meta {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-2);'
    + '  margin-bottom: 6px;'
    + '}'
    + '.decidr-dash-proj-stat {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  font-size: 11px;'
    + '  color: var(--text-tertiary);'
    + '}'
    + '.decidr-dash-proj-stat .decidr-inline-icon { display: inline-flex; color: var(--text-tertiary); }'
    + '.decidr-dash-proj-stat .decidr-inline-icon svg { width: 12px; height: 12px; }'
    + '.decidr-dash-proj-owner {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '  font-size: 11px;'
    + '  color: var(--text-secondary);'
    + '  margin-bottom: 4px;'
    + '}'
    + '.decidr-dash-proj-owner-avatar {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  width: 16px;'
    + '  height: 16px;'
    + '  border-radius: 50%;'
    + '  font-size: 8px;'
    + '  font-weight: var(--weight-bold);'
    + '  color: #fff;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-dash-proj-badge {'
    + '  display: inline-block;'
    + '  padding: 1px 6px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  font-size: 10px;'
    + '  font-weight: var(--weight-semibold);'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.03em;'
    + '}'
    + '.decidr-dash-proj-badge-owner { background: rgba(99,102,241,0.15); color: #818cf8; }'
    + '.decidr-dash-proj-badge-pending { background: rgba(245,158,11,0.15); color: #f59e0b; }'
    + ''
    + '/* ─── Dashboard: Section Spacing ─── */'
    + '.decidr-section + .decidr-section { margin-top: var(--space-6); }'
    + '.decidr-init-projects { margin-top: var(--space-2); margin-bottom: var(--space-4); }'
    + '.decidr-init-card { margin-bottom: var(--space-3); }'
    + '.decidr-dash-proj-badge-review { background: rgba(239,68,68,0.15); color: #ef4444; }'
    + ''
    + '/* ─── Graph: Project Card (SVG foreignObject) ─── */'
    + '.decidr-graph-proj-card {'
    + '  width: 100%;'
    + '  height: 100%;'
    + '  background: var(--glass-bg-heavy);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-left: 3px solid var(--entity-project);'
    + '  border-radius: var(--border-radius-lg);'
    + '  padding: var(--space-3);'
    + '  box-sizing: border-box;'
    + '  font-family: Figtree, -apple-system, BlinkMacSystemFont, sans-serif;'
    + '  cursor: pointer;'
    + '  display: flex;'
    + '  flex-direction: column;'
    + '  gap: 4px;'
    + '}'
    + '.decidr-graph-proj-card-name {'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '  white-space: nowrap;'
    + '  overflow: hidden;'
    + '  text-overflow: ellipsis;'
    + '}'
    + '.decidr-graph-proj-card-owner {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  font-size: 10px;'
    + '  color: var(--text-secondary);'
    + '}'
    + '.decidr-graph-proj-card-avatar {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  width: 18px;'
    + '  height: 18px;'
    + '  border-radius: 50%;'
    + '  font-size: 8px;'
    + '  font-weight: var(--weight-bold);'
    + '  color: #fff;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-graph-proj-card-footer {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: space-between;'
    + '  font-size: 10px;'
    + '  color: var(--text-tertiary);'
    + '  margin-top: auto;'
    + '}'
    + '.decidr-graph-proj-card-status {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 4px;'
    + '}'
    + '.decidr-graph-proj-card-dot {'
    + '  width: 6px;'
    + '  height: 6px;'
    + '  border-radius: 50%;'
    + '  flex-shrink: 0;'
    + '}'
    + ''
    + '/* ─── Graph: Summary Card Elements ─── */'
    + '.decidr-graph-summary-owners {'
    + '  display: flex;'
    + '  gap: 10px;'
    + '  flex-wrap: wrap;'
    + '  justify-content: center;'
    + '}'
    + '.decidr-graph-summary-owner-pill {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 10px;'
    + '  padding: 8px 20px 8px 8px;'
    + '  border-radius: 28px;'
    + '  background: rgba(255,255,255,0.08);'
    + '  border: 1px solid rgba(255,255,255,0.1);'
    + '}'
    + '.decidr-graph-summary-avatar {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  width: 36px;'
    + '  height: 36px;'
    + '  border-radius: 50%;'
    + '  font-size: 14px;'
    + '  font-weight: var(--weight-bold);'
    + '  color: #fff;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-graph-summary-owner-name {'
    + '  font-size: 20px;'
    + '  color: rgba(255,255,255,0.8);'
    + '  font-weight: var(--weight-medium);'
    + '}'
    + '.decidr-graph-summary-bar-wrap {'
    + '  width: 90%;'
    + '  max-width: 460px;'
    + '}'
    + '.decidr-graph-summary-section-label {'
    + '  font-size: 18px;'
    + '  color: var(--text-tertiary);'
    + '  margin-bottom: 10px;'
    + '  text-transform: uppercase;'
    + '  letter-spacing: 0.05em;'
    + '  text-align: center;'
    + '  font-weight: var(--weight-semibold);'
    + '}'
    + '.decidr-graph-summary-bar {'
    + '  display: flex;'
    + '  height: 14px;'
    + '  border-radius: 7px;'
    + '  overflow: hidden;'
    + '  background: var(--glass-bg);'
    + '}'
    + '.decidr-graph-summary-legend {'
    + '  display: flex;'
    + '  gap: 16px;'
    + '  justify-content: center;'
    + '  margin-top: 10px;'
    + '  font-size: 18px;'
    + '}'
    + '.decidr-graph-summary-legend-item {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  color: var(--text-tertiary);'
    + '}'
    + '.decidr-graph-summary-legend-dot {'
    + '  width: 10px;'
    + '  height: 10px;'
    + '  border-radius: 50%;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-graph-summary-stages {'
    + '  text-align: center;'
    + '}'
    + '.decidr-graph-summary-stage-pills {'
    + '  display: flex;'
    + '  gap: 8px;'
    + '  flex-wrap: wrap;'
    + '  justify-content: center;'
    + '  margin-top: 8px;'
    + '}'
    + '.decidr-graph-summary-stage-pill {'
    + '  display: inline-block;'
    + '  padding: 4px 12px;'
    + '  border-radius: var(--border-radius-pill);'
    + '  font-size: 16px;'
    + '  font-weight: var(--weight-medium);'
    + '}'
    + ''
    + '/* ─── Graph: Detail Strip ─── */'
    + '.decidr-graph-detail-strip {'
    + '  display: none;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  padding: var(--space-3) var(--space-4);'
    + '  border-top: 1px solid var(--border-default);'
    + '  background: var(--bg-surface-subtle);'
    + '  flex-shrink: 0;'
    + '  min-height: 48px;'
    + '  flex-wrap: wrap;'
    + '}'
    + '.decidr-graph-detail-strip-visible {'
    + '  display: flex;'
    + '}'
    + '.decidr-graph-detail-strip-label {'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-tertiary);'
    + '  margin-right: var(--space-1);'
    + '}'
    + '.decidr-graph-detail-strip-name {'
    + '  font-size: var(--text-body);'
    + '  font-weight: var(--weight-semibold);'
    + '  color: var(--text-primary);'
    + '}'
    + '.decidr-graph-detail-strip-spacer {'
    + '  flex: 1;'
    + '}'
    + '.decidr-graph-detail-strip-meta {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: var(--space-3);'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-secondary);'
    + '}'
    + ''
    + '/* ─── Graph: Tooltip ─── */'
    + '.decidr-graph-tooltip {'
    + '  position: absolute;'
    + '  padding: 6px 10px;'
    + '  background: var(--glass-bg-heavy);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-sm);'
    + '  font-size: var(--text-small);'
    + '  color: var(--text-primary);'
    + '  pointer-events: none;'
    + '  white-space: nowrap;'
    + '  z-index: 100;'
    + '  opacity: 0;'
    + '  transition: opacity var(--transition-fast);'
    + '  box-shadow: var(--glass-shadow);'
    + '  font-family: var(--font-sans);'
    + '}'
    + '.decidr-graph-tooltip-visible {'
    + '  opacity: 1;'
    + '}'
    + ''
    + '/* ─── Graph: Modal ─── */'
    + '.decidr-graph-modal-overlay {'
    + '  position: absolute;'
    + '  inset: 0;'
    + '  background: rgba(0,0,0,0.5);'
    + '  z-index: 200;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '}'
    + '.decidr-graph-modal {'
    + '  background: var(--bg-app);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-lg);'
    + '  padding: var(--space-6);'
    + '  width: 400px;'
    + '  max-width: 90%;'
    + '  box-shadow: 0 16px 48px rgba(0,0,0,0.5);'
    + '}'
    + '.decidr-graph-modal h3 {'
    + '  font-size: var(--text-h3);'
    + '  font-weight: var(--weight-bold);'
    + '  color: var(--text-primary);'
    + '  margin: 0 0 var(--space-4) 0;'
    + '}'
    + '.decidr-graph-modal label {'
    + '  display: block;'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-medium);'
    + '  color: var(--text-secondary);'
    + '  margin-bottom: var(--space-1);'
    + '}'
    + '.decidr-graph-modal input,'
    + '.decidr-graph-modal select {'
    + '  width: 100%;'
    + '  padding: 8px 12px;'
    + '  margin-bottom: var(--space-3);'
    + '  background: var(--glass-bg);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  color: var(--text-primary);'
    + '  font-family: inherit;'
    + '  font-size: var(--text-body);'
    + '  box-sizing: border-box;'
    + '}'
    + '.decidr-graph-modal input:focus,'
    + '.decidr-graph-modal select:focus {'
    + '  outline: none;'
    + '  border-color: var(--accent-primary);'
    + '  box-shadow: 0 0 0 3px rgba(96,165,250,0.15);'
    + '}'
    + '.decidr-graph-modal-actions {'
    + '  display: flex;'
    + '  justify-content: flex-end;'
    + '  gap: var(--space-2);'
    + '  margin-top: var(--space-4);'
    + '}'
    + '.decidr-graph-modal-actions button {'
    + '  padding: 8px 16px;'
    + '  border-radius: var(--border-radius-md);'
    + '  font-family: inherit;'
    + '  font-size: var(--text-small);'
    + '  font-weight: var(--weight-semibold);'
    + '  cursor: pointer;'
    + '  border: 1px solid var(--glass-border);'
    + '  transition: all var(--transition-fast);'
    + '}'
    + '.decidr-graph-modal-btn-cancel {'
    + '  background: var(--glass-bg);'
    + '  color: var(--text-secondary);'
    + '}'
    + '.decidr-graph-modal-btn-cancel:hover {'
    + '  background: var(--glass-bg-heavy);'
    + '}'
    + '.decidr-graph-modal-btn-create {'
    + '  background: var(--accent-primary);'
    + '  color: #fff;'
    + '  border-color: var(--accent-primary);'
    + '}'
    + '.decidr-graph-modal-btn-create:hover {'
    + '  background: var(--accent-primary-hover);'
    + '}'
    + '.decidr-graph-modal-color-dot {'
    + '  width: 24px;'
    + '  height: 24px;'
    + '  border-radius: 50%;'
    + '  display: inline-block;'
    + '  cursor: pointer;'
    + '  border: 2px solid transparent;'
    + '  transition: border-color var(--transition-fast);'
    + '}'
    + ''
    + '/* ─── Graph: Zoom Controls ─── */'
    + '.decidr-graph-zoom-btn {'
    + '  width: 32px;'
    + '  height: 32px;'
    + '  border-radius: var(--border-radius-md);'
    + '  border: 1px solid var(--glass-border);'
    + '  background: var(--glass-bg);'
    + '  color: var(--text-primary);'
    + '  cursor: pointer;'
    + '  font-size: 18px;'
    + '  display: flex;'
    + '  align-items: center;'
    + '  justify-content: center;'
    + '  transition: background var(--transition-fast);'
    + '}'
    + '.decidr-graph-zoom-btn:hover {'
    + '  background: var(--glass-bg-heavy);'
    + '}'
    + ''
    + '@media (prefers-color-scheme: light) {'
    + '  .decidr-graph-summary-owner-pill {'
    + '    background: rgba(0,0,0,0.05);'
    + '    border-color: rgba(0,0,0,0.08);'
    + '  }'
    + '  .decidr-graph-summary-owner-name {'
    + '    color: rgba(0,0,0,0.7);'
    + '  }'
    + '}';

    + ''
    + '/* ── Org Picker ─────────────────────────────────────── */'
    + '.decidr-org-picker {'
    + '  position: relative;'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '}'
    + '.decidr-org-picker-btn {'
    + '  display: inline-flex;'
    + '  align-items: center;'
    + '  gap: 6px;'
    + '  padding: 6px 12px;'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  background: var(--glass-bg);'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  font-family: var(--font-sans);'
    + '  cursor: pointer;'
    + '  transition: border-color 0.15s ease, background 0.15s ease;'
    + '}'
    + '.decidr-org-picker-btn:hover {'
    + '  border-color: var(--accent-primary);'
    + '  background: var(--bg-surface-hover);'
    + '}'
    + '.decidr-org-picker-menu {'
    + '  display: none;'
    + '  position: absolute;'
    + '  top: calc(100% + 4px);'
    + '  left: 0;'
    + '  z-index: 100;'
    + '  min-width: 220px;'
    + '  max-height: 280px;'
    + '  overflow-y: auto;'
    + '  background: var(--bg-surface);'
    + '  border: 1px solid var(--glass-border);'
    + '  border-radius: var(--border-radius-md);'
    + '  box-shadow: var(--glass-shadow);'
    + '  padding: 4px;'
    + '}'
    + '.decidr-org-picker-menu.open {'
    + '  display: block;'
    + '}'
    + '.decidr-org-picker-option {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  width: 100%;'
    + '  padding: 8px 12px;'
    + '  border: none;'
    + '  border-radius: var(--border-radius-sm);'
    + '  background: transparent;'
    + '  color: var(--text-primary);'
    + '  font-size: var(--text-small);'
    + '  font-family: var(--font-sans);'
    + '  cursor: pointer;'
    + '  text-align: left;'
    + '}'
    + '.decidr-org-picker-option:hover {'
    + '  background: var(--glass-bg);'
    + '}'
    + '.decidr-org-picker-option.active {'
    + '  background: rgba(59,130,246,0.1);'
    + '  font-weight: var(--weight-medium);'
    + '}'
    + '.decidr-org-picker-dot {'
    + '  width: 8px;'
    + '  height: 8px;'
    + '  border-radius: 50%;'
    + '  flex-shrink: 0;'
    + '}'
    + '.decidr-org-picker-dot.valid { background: var(--entity-bridge); }'
    + '.decidr-org-picker-dot.expired { background: var(--priority-medium); }'
    + '.decidr-org-picker-dot.no-token { background: var(--text-tertiary); }'
    + '.decidr-org-picker-auth {'
    + '  display: flex;'
    + '  align-items: center;'
    + '  gap: 8px;'
    + '  width: 100%;'
    + '  padding: 8px 12px;'
    + '  margin-top: 4px;'
    + '  border: 1px dashed var(--glass-border);'
    + '  border-radius: var(--border-radius-sm);'
    + '  background: transparent;'
    + '  color: var(--text-secondary);'
    + '  font-size: var(--text-xs);'
    + '  font-family: var(--font-sans);'
    + '  cursor: pointer;'
    + '  text-align: left;'
    + '}'
    + '.decidr-org-picker-auth:hover {'
    + '  border-color: var(--accent-primary);'
    + '  color: var(--accent-primary);'
    + '}'
    + '.decidr-org-picker-chevron {'
    + '  transition: transform 0.15s ease;'
    + '}'
    + '/* GitHub dashboard badge color variants */'
    + '.decidr-gh-badge-issues { background: rgba(34,197,94,0.15); color: var(--color-success); }'
    + '.decidr-gh-badge-prs { background: rgba(99,102,241,0.15); color: #818cf8; }'
    + '.decidr-gh-badge-review { background: rgba(245,158,11,0.15); color: #f59e0b; }';

  style.textContent = css;
  document.head.appendChild(style);
})();
